//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace terraservice.Exception {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("terraservice.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string INVALID_LOGGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGGIN", resourceCulture);
            }
        }
        
        public static string PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("PASSWORD_ERROR", resourceCulture);
            }
        }
        
        public static string EMAIL_ALREDY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREDY_EXISTS", resourceCulture);
            }
        }
        
        public static string CLIENT_NAME_NULL {
            get {
                return ResourceManager.GetString("CLIENT_NAME_NULL", resourceCulture);
            }
        }
        
        public static string CLIENT_NAME_ALREDY_EXISTS {
            get {
                return ResourceManager.GetString("CLIENT_NAME_ALREDY_EXISTS", resourceCulture);
            }
        }
        
        public static string CLIENT_DOESENT_EXIST {
            get {
                return ResourceManager.GetString("CLIENT_DOESENT_EXIST", resourceCulture);
            }
        }
        
        public static string EMPTY_LIST_CLIENTS {
            get {
                return ResourceManager.GetString("EMPTY_LIST_CLIENTS", resourceCulture);
            }
        }
        
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        public static string UNKNWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNWN_ERROR", resourceCulture);
            }
        }
        
        public static string REGISTER_ALREDY_EXISTS {
            get {
                return ResourceManager.GetString("REGISTER_ALREDY_EXISTS", resourceCulture);
            }
        }
        
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string MISSING_FIELDS {
            get {
                return ResourceManager.GetString("MISSING_FIELDS", resourceCulture);
            }
        }
        
        public static string MORE_THEN_TREE_ELEMENTS {
            get {
                return ResourceManager.GetString("MORE_THEN_TREE_ELEMENTS", resourceCulture);
            }
        }
        
        public static string NAME_EXIST {
            get {
                return ResourceManager.GetString("NAME_EXIST", resourceCulture);
            }
        }
    }
}
